name: Deploy Gracespringportal Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Sync files & Restart PM2
        run: |
          rsync -avz --delete --exclude='.git' --exclude='node_modules' ./ /var/www/portal/
          cd /var/www/portal
          npm install --production
          pm2 restart "portal" || pm2 start npm --name "portal" -- run start -- -p 3002
          pm2 save


          



# name: Deploy NextJS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Next App
#         run: npm run build

#       - name: Restart PM2
#         run: |
#           pm2 delete pGSH || true
#           pm2 start npm --name "pGSH" -- start
#           pm2 save
          
      # - name: Restart PM2
      #   run: |
      #     pm2 delete pGSH || true
      #     pm2 start npm --name "pGSH" -- start
      #     pm2 save,

      # - name: Restart PM2
      #   run: |
      #     pm2 delete pGSH || true
      #     pm2 start npm --name "pGSH" -- start
      #     pm2 save